dofile_once("mods/modloader/files/serialization.lua")

MODLOADER_GE_HANDLERS_LAST = MODLOADER_GE_HANDLERS_LAST or {}
MODLOADER_GE_HANDLERS_ALL = MODLOADER_GE_HANDLERS_ALL or {}
MODLOADER_GE_CURRENT_MOD = MODLOADER_GE_CURRENT_MOD or nil

function handler(fn)
    MODLOADER_GE_HANDLERS_LAST[MODLOADER_GE_CURRENT_MOD] = fn
end

function handler_all(fn)
    MODLOADER_GE_HANDLERS_ALL[MODLOADER_GE_CURRENT_MOD] = fn
end
